CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  password_hash VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS moods(
  id SERIAL PRIMARY KEY,
  mood_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS foods(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  calories INT
);

CREATE TABLE IF NOT EXISTS suggestions(
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  mood_id INT NOT NULL REFERENCES moods(id),
  food_id INT NOT NULL REFERENCES foods(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, mood_id)
);


  